### ISSUE TITLE
Pagamentos brasileiros 

### ISSUE THREAD

**Issue by joinasau** [Next-Panel/Jexactyl-BR#2]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Favor, adicione novos métodos de pagamentos brasileiros. Como mercado pago ou outro.

**Comment by Ashu11-A** [comment]
Opa, tentamos o mercado pago, mas depois de muita tentativa não tivemos sucesso.

**Comment by Ashu11-A** [comment]
Estou pesquisando mais afundo, talvez eu tente novamente futuramente

**Comment by joinasau** [comment]
O foda é que não vale apena usar paypal, infelizmente. Tente picpay ou mercado pago

**Comment by Ashu11-A** [comment]
Stripe aceita até boleto, pix etc, só precisa confirmar a conta com um documento, eu e o Drylian tentamos íntegrar o Mercado Pago, mas por falta de conhecimento em cima do Laravel(linguagem que o painel é construído) não conseguimos

**Comment by Ashu11-A** [comment]
E como comentado pelo Jex no Discord, ele não irá mais adicionar formas de pagamento, somente irá manter funcionando

**Comment by drysius** [comment]
espero um dia poder colocar pagamentos brasileiros no painel mais infelizmente ainda falta conhecimento base sobre api do laravel, se fosse um ou dois arquivos até seria facil adicionar, mais infelizmente só de base tem 12 + os outros de funcionamento, então pelo menos por enquanto.

**Comment by Ashu11-A** [comment]
Além de ter que estudar como a API do mercado pago é implementada, Endpoints etc... Também pelo o que eu pesquisei, o Mercado Pago PHP só tem suporte oficial para PHP7 (o painel usa PHP8.1), mas acredito que dê para implementar, só falta conhecimento

**Comment by joinasau** [comment]
Depois de um bom tempo, acho que vocês conseguem adicionar. Enfim reabrindo a issue para quem sabe algo novo nos pagamentos.

**Comment by joinasau** [comment]
https://github.com/livepixel/mercado-pago

**Comment by drysius** [comment]
reabrindo para te dizer que o pagamento foi adicionado, estou fazendo algumas verificações a mais para reparar alguns erros internos, porem o codigo ja se encontra na developer caso voce queira ver
