### ISSUE TITLE
Erro de Tradução - Aceitar o EULA

### ISSUE THREAD

**Issue by oliiveiraaa** [Next-Panel/Jexactyl-BR#219]
### Comportamento atual

O título que aparece no pop-up:
Aceitar o ® EULA do **minecraftt**

### Comportamento esperado

O título que deveria aparecer no pop-up:
Aceitar o ® EULA do **minecraft**

### Passos para Reproduzir

Iniciar um servidor minecraft pela primeira vez.

### Versão do painel

latest

### Versão da Wings

latest

### Existe algum problema para isso?

- [X] Pesquisei as questões existentes antes de abrir este assunto.
- [X] Eu verifiquei no servidor Discord e acredito que este é um bug com o software, e não um problema de configuração com meu sistema específico.

**Comment by oliiveiraaa** [comment]
Outro erro de tradução:
Quando você apaga o servidor e da F5 no link do console do mesmo aparece:

Algo deu errado
The requested resource could not be found on the server.

**Comment by oliiveiraaa** [comment]
Outro erro de tradução:
Quando se tenta criar um servidor e você não tem os recursos, aparece a seguinte mensagem no campo de formulário:

Cpu must be greater than or equal to 25
Memory must be less than or equal to 0
Disk must be greater than or equal to 256

**Comment by Ashu11-A** [comment]
ok, vou olhar o código para corrigir as traduções

**Comment by Ashu11-A** [comment]
Os campos dos formulários vem da biblioteca [yup](https://www.npmjs.com/package/yup), adicionei uma biblioteca adicional, a [yup-locales](https://www.npmjs.com/package/yup-locales), as outras traduções foram passadas despercebidas, caso encontre mais erros, por favor, abra um novo Issues

[#13c74db](https://github.com/Next-Panel/Jexactyl-BR/commit/13c74dbbd224928f7ab901b0e515c2ef0a795555)

![image](https://github.com/Next-Panel/Jexactyl-BR/assets/30575805/dc669013-6e0a-4d12-a770-b7a4bcff5f2b)
