### ISSUE TITLE
erro na tradução

### ISSUE THREAD

**Issue by pedrorchagas** [Next-Panel/Jexactyl-BR#22]
### Comportamento atual

erro na tradução na aba de usuários, especificamente em "utualizar usuário" 

### Comportamento esperado

o esperado é ser "atualizar usuário"

### Passos para Reproduzir

ir na aba principal de usuário

### Versão do painel

3.7.0

### Versão da Wings

1.11.0

### Logs de erros

```bash
https://imgur.com/a/BRWizOZ
```

### Existe algum problema para isso?

- [X] Pesquisei as questões existentes antes de abrir este assunto.
- [X] Eu verifiquei no servidor Discord e acredito que este é um bug com o software, e não um problema de configuração com meu sistema específico.

**Comment by Ashu11-A** [comment]
Corrigido
